baseURL = 'https://www.green-coding.berlin/'
languageCode = 'de-en'
title = 'green-coding.berlin'

paginate = 10
paginatePath = "page"

summaryLength = 30

# Minify removes also the "" (quotes) from the HTML tags. This breaks bing site validation and
# also maybe some SEO features.
[minify]
  minifyOutput = false

[outputs]
  home = ['HTML']
  # home = ['HTML', 'CSS'] # if you want to render CSS for a normal page, please also set this rule acccordingly

[taxonomies]
  tag = ""
  group = ""
  category = ""