baseURL = 'https://www.green-coding.io/'
title = 'green-coding.io'

defaultContentLanguageInSubdir = false

pagination.pagerSize = 10
pagination.path = "page"

summaryLength = 30

defaultContentLanguage = "en"

buildFuture = true

[build]
  writeStats = true

[languages]
  [languages.en]
    disabled = false
    languageCode = "de-EN"
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1

  [languages.de]
    languageCode = "de-DE"
    disabled = false
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2



# Minify removes also the "" (quotes) from the HTML tags. This breaks bing site validation and
# also maybe some SEO features.
[minify]
  minifyOutput = false

[outputs]
  home = ['HTML']
  # home = ['HTML', 'CSS'] # if you want to render CSS for a normal page, please also set this rule acccordingly

[taxonomies]
  tag = ""
  group = ""
  category = ""

# This will allow HTML tags inside of .md files without hacks like {{<rawhtml>}}
[markup.goldmark.renderer]
  unsafe = true
